'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useAppStore } from '@/lib/store';
import { ArrowLeft, BookOpen, ChevronDown, CheckCircle2, Quote, AlertTriangle, Lightbulb, GraduationCap, ClipboardList } from 'lucide-react';
import Link from 'next/link';

type Lang = 'en' | 'hi';

interface TopicNote {
  id: string;
  num: number;
  title: [string, string];
  introduction: [string, string];
  concepts: { heading: [string, string]; body: [string, string] }[];
  quotes: [string, string][];
  evaluation: [string, string];
  conclusion: [string, string];
  shortQ: [string, string][];
  longQ: [string, string][];
  mcqs: { q: [string, string]; opts: [string, string][]; correct: number }[];
  ugcNotes: [string, string];
  ugcQ: [string, string][];
}

/* ─── NOTES PLACEHOLDER ─── */
const NOTES: TopicNote[] = [];

export default function PaperPage() {
  const { language } = useAppStore();
  const [expandedTopic, setExpandedTopic] = useState<string | null>(null);

  const t = (en: string, hi: string) => language === 'en' ? en : hi;

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950 pb-16">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 py-6">
        
        {/* Top Navigation & Header */}
        <div className="mb-6">
          <div className="flex items-center gap-3 mb-4">
            <Link href="/syllabus#sem4" className="p-2 rounded-xl hover:bg-gray-200 dark:hover:bg-gray-800 transition-colors">
              <ArrowLeft className="w-5 h-5" />
            </Link>
            <div>
              <h1 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
                PSCE-414B: Foreign Policy of Major Powers
              </h1>
              <p className="text-gray-500 dark:text-gray-400 flex items-center gap-2 text-sm sm:text-base">
                PG Semester IV — Detailed Bilingual Notes
              </p>
            </div>
          </div>
          
          <div className="bg-gradient-to-r from-rose-600 to-pink-700 rounded-2xl p-6 text-white shadow-sm">
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center text-2xl shrink-0">
                📚
              </div>
              <div>
                <div className="font-mono text-rose-100 text-sm mb-1 font-bold tracking-wider">PAPER CODE: PSCE-414B</div>
                <div className="text-sm text-rose-50/90 leading-relaxed">
                  5 Credits | 60 Lectures + 15 Tutorials | Full Marks: 100 (End Sem: 70 + Internal: 30) | {NOTES.length} Topics
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Content Warning (if no notes) */}
        {NOTES.length === 0 && (
          <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-2xl p-6 text-center">
            <AlertTriangle className="w-8 h-8 text-amber-500 mx-auto mb-3" />
            <h3 className="text-amber-800 dark:text-amber-400 font-bold mb-1">Content Generating</h3>
            <p className="text-amber-600 dark:text-amber-500 text-sm">
              The detailed bilingual notes for this paper are currently being generated by our AI system. Please check back shortly.
            </p>
          </div>
        )}

        {/* Topics Accordion */}
        <div className="space-y-4">
          {NOTES.map((topic) => {
            const isExpanded = expandedTopic === topic.id;
            
            return (
              <div 
                key={topic.id}
                className={`bg-white dark:bg-gray-900 rounded-2xl border transition-all duration-200 overflow-hidden shadow-sm ${
                  isExpanded 
                    ? 'border-rose-400 dark:border-rose-600 ring-4 ring-rose-50 dark:ring-rose-900/20' 
                    : 'border-gray-100 dark:border-gray-800 hover:border-gray-200 dark:hover:border-gray-700'
                }`}
              >
                {/* Accordion Header */}
                <button
                  onClick={() => setExpandedTopic(isExpanded ? null : topic.id)}
                  className="w-full p-4 sm:p-5 flex items-center justify-between text-left"
                >
                  <div className="flex items-center gap-4">
                    <div className={`w-10 h-10 rounded-xl flex items-center justify-center font-bold text-sm shrink-0 transition-colors ${
                      isExpanded 
                        ? 'bg-rose-600 text-white shadow-md' 
                        : 'bg-rose-100 dark:bg-rose-900/50 text-rose-700 dark:text-rose-400'
                    }`}>
                      {topic.num}
                    </div>
                    <div>
                      <h2 className="font-semibold text-gray-900 dark:text-white text-base md:text-lg text-justify">
                        {t(topic.title[0], topic.title[1])}
                      </h2>
                      <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                        5-Part Structure | MCQ | UGC NET Prep
                      </p>
                    </div>
                  </div>
                  <ChevronDown className={`w-5 h-5 text-gray-400 transition-transform duration-300 shrink-0 ${
                    isExpanded ? 'rotate-180 text-rose-600 dark:text-rose-400' : ''
                  }`} />
                </button>

                {/* Accordion Body */}
                <AnimatePresence>
                  {isExpanded && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3, ease: 'easeInOut' }}
                      className="overflow-hidden border-t border-gray-100 dark:border-gray-800"
                    >
                      <div className="p-4 sm:p-6 space-y-8 bg-gray-50/50 dark:bg-gray-900/50">
                        
                        {/* 1. Introduction */}
                        <section>
                          <div className="flex items-center gap-2 mb-3">
                            <div className="w-6 h-6 rounded-full bg-blue-100 dark:bg-blue-900/50 flex items-center justify-center text-blue-600 dark:text-blue-400 text-xs font-bold">1</div>
                            <h3 className="font-bold text-blue-800 dark:text-blue-300">
                              {t('Introduction', 'परिचय')}
                            </h3>
                          </div>
                          <p className="text-base text-justify text-gray-700 dark:text-gray-300 leading-relaxed whitespace-pre-line">
                            {t(topic.introduction[0], topic.introduction[1])}
                          </p>
                        </section>

                        {/* 2. Core Concepts */}
                        <section>
                          <div className="flex items-center gap-2 mb-4">
                            <div className="w-6 h-6 rounded-full bg-emerald-100 dark:bg-emerald-900/50 flex items-center justify-center text-emerald-600 dark:text-emerald-400 text-xs font-bold">2</div>
                            <h3 className="font-bold text-emerald-800 dark:text-emerald-300">
                              {t('Core Concepts', 'मुख्य सिद्धांत')}
                            </h3>
                          </div>
                          <div className="space-y-4">
                            {topic.concepts.map((concept, idx) => (
                              <div key={idx} className="bg-white dark:bg-gray-800 p-4 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700">
                                <h4 className="font-semibold text-gray-900 dark:text-white mb-2 pb-2 border-b border-gray-100 dark:border-gray-700">
                                  {t(concept.heading[0], concept.heading[1])}
                                </h4>
                                <p className="text-base text-justify text-gray-700 dark:text-gray-300 leading-relaxed whitespace-pre-line">
                                  {t(concept.body[0], concept.body[1])}
                                </p>
                              </div>
                            ))}
                          </div>
                        </section>

                        {/* 3. Quotes & References */}
                        <section>
                          <div className="flex items-center gap-2 mb-4">
                            <div className="w-6 h-6 rounded-full bg-purple-100 dark:bg-purple-900/50 flex items-center justify-center text-purple-600 dark:text-purple-400 text-xs font-bold">3</div>
                            <h3 className="font-bold text-purple-800 dark:text-purple-300">
                              {t('Scholarly Quotes & References', 'विद्वानों के उद्धरण और संदर्भ')}
                            </h3>
                          </div>
                          <div className="grid gap-3">
                            {topic.quotes.map((quote, idx) => (
                              <div key={idx} className="flex gap-3 bg-purple-50 dark:bg-purple-900/20 p-4 rounded-xl border border-purple-100 dark:border-purple-800/30">
                                <Quote className="w-5 h-5 text-purple-400 shrink-0" />
                                <p className="text-base italic text-justify text-gray-700 dark:text-gray-300">
                                  {t(quote[0], quote[1])}
                                </p>
                              </div>
                            ))}
                          </div>
                        </section>

                        {/* 4. Critical Evaluation */}
                        <section>
                          <div className="flex items-center gap-2 mb-3">
                            <div className="w-6 h-6 rounded-full bg-orange-100 dark:bg-orange-900/50 flex items-center justify-center text-orange-600 dark:text-orange-400 text-xs font-bold">4</div>
                            <h3 className="font-bold text-orange-800 dark:text-orange-300">
                              {t('Critical Evaluation', 'आलोचनात्मक मूल्यांकन')}
                            </h3>
                          </div>
                          <p className="text-base text-justify text-gray-700 dark:text-gray-300 leading-relaxed whitespace-pre-line">
                            {t(topic.evaluation[0], topic.evaluation[1])}
                          </p>
                        </section>

                        {/* 5. Conclusion */}
                        <section>
                          <div className="flex items-center gap-2 mb-3">
                            <div className="w-6 h-6 rounded-full bg-teal-100 dark:bg-teal-900/50 flex items-center justify-center text-teal-600 dark:text-teal-400 text-xs font-bold">5</div>
                            <h3 className="font-bold text-teal-800 dark:text-teal-300">
                              {t('Conclusion', 'निष्कर्ष')}
                            </h3>
                          </div>
                          <p className="text-base text-justify text-gray-700 dark:text-gray-300 leading-relaxed whitespace-pre-line">
                            {t(topic.conclusion[0], topic.conclusion[1])}
                          </p>
                        </section>

                        <hr className="border-gray-200 dark:border-gray-800 my-6" />

                        {/* REVISION BOOSTER */}
                        <section className="bg-gradient-to-br from-indigo-50 to-blue-50 dark:from-indigo-950/30 dark:to-blue-900/20 rounded-2xl p-5 border border-indigo-100 dark:border-indigo-800/30">
                          <div className="flex items-center gap-3 mb-6 pb-4 border-b border-indigo-200 dark:border-indigo-800">
                            <div className="p-2 bg-indigo-100 dark:bg-indigo-900/50 rounded-lg">
                              <Lightbulb className="w-6 h-6 text-indigo-600 dark:text-indigo-400" />
                            </div>
                            <div>
                              <h3 className="font-bold text-lg text-indigo-900 dark:text-indigo-300">
                                {t('Revision Booster', 'रिवीजन बूस्टर')}
                              </h3>
                              <p className="text-xs text-indigo-700 dark:text-indigo-400">
                                Exam-oriented expected questions & MCQs
                              </p>
                            </div>
                          </div>

                          <div className="grid md:grid-cols-2 gap-6 mb-6">
                            {/* Short Questions */}
                            <div>
                              <h4 className="font-bold text-gray-900 dark:text-white mb-3 flex items-center gap-2">
                                <ClipboardList className="w-4 h-4 text-indigo-500" />
                                {t('Expected Short Questions', 'संभावित लघु उत्तरीय प्रश्न')}
                              </h4>
                              <ul className="space-y-2">
                                {topic.shortQ.map((q, idx) => (
                                  <li key={idx} className="flex gap-2 text-base text-justify text-gray-700 dark:text-gray-300">
                                    <span className="font-bold text-indigo-400">{idx + 1}.</span>
                                    {t(q[0], q[1])}
                                  </li>
                                ))}
                              </ul>
                            </div>
                            
                            {/* Long Questions */}
                            <div>
                              <h4 className="font-bold text-gray-900 dark:text-white mb-3 flex items-center gap-2">
                                <BookOpen className="w-4 h-4 text-indigo-500" />
                                {t('Expected Long Questions', 'संभावित दीर्घ उत्तरीय प्रश्न')}
                              </h4>
                              <ul className="space-y-2">
                                {topic.longQ.map((q, idx) => (
                                  <li key={idx} className="flex gap-2 text-base text-justify text-gray-700 dark:text-gray-300">
                                    <span className="font-bold text-indigo-400">{idx + 1}.</span>
                                    {t(q[0], q[1])}
                                  </li>
                                ))}
                              </ul>
                            </div>
                          </div>

                          {/* MCQs */}
                          <div className="bg-white dark:bg-gray-900 rounded-xl p-4 shadow-sm">
                            <h4 className="font-bold text-gray-900 dark:text-white mb-4 flex items-center gap-2 border-b border-gray-100 dark:border-gray-800 pb-2">
                              <CheckCircle2 className="w-5 h-5 text-green-500" />
                              {t('Multiple Choice Questions', 'बहुविकल्पीय प्रश्न')}
                            </h4>
                            <div className="space-y-6">
                              {topic.mcqs.map((mcq, idx) => (
                                <div key={idx}>
                                  <p className="font-medium text-gray-900 dark:text-white mb-2">
                                    {idx + 1}. {t(mcq.q[0], mcq.q[1])}
                                  </p>
                                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                                    {mcq.opts.map((opt, oIdx) => (
                                      <div 
                                        key={oIdx}
                                        className={`px-3 py-2 rounded-lg border text-base text-justify ${
                                          oIdx === mcq.correct
                                            ? 'bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800 text-green-800 dark:text-green-300 font-medium'
                                            : 'bg-gray-50 dark:bg-gray-800/50 border-gray-100 dark:border-gray-700 text-gray-600 dark:text-gray-400'
                                        }`}
                                      >
                                        <span className="mr-2 font-bold opacity-50">
                                          {['A', 'B', 'C', 'D'][oIdx]}
                                        </span>
                                        {t(opt[0], opt[1])}
                                        {oIdx === mcq.correct && (
                                          <CheckCircle2 className="w-4 h-4 inline-block float-right text-green-500" />
                                        )}
                                      </div>
                                    ))}
                                  </div>
                                </div>
                              ))}
                            </div>
                          </div>
                        </section>

                        {/* UGC NET PREP */}
                        <section className="bg-gradient-to-r from-amber-50 to-orange-50 dark:from-amber-950/20 dark:to-orange-950/20 rounded-2xl p-5 border border-amber-100 dark:border-amber-900/30">
                          <div className="flex items-center gap-3 mb-4">
                            <div className="p-2 bg-amber-100 dark:bg-amber-900/50 rounded-lg">
                              <GraduationCap className="w-6 h-6 text-amber-600 dark:text-amber-400" />
                            </div>
                            <h3 className="font-bold text-lg text-amber-900 dark:text-amber-300">
                              UGC NET / JRF Preparation
                            </h3>
                          </div>
                          
                          <div className="space-y-4">
                            <div className="bg-white/60 dark:bg-gray-900/50 rounded-xl p-4">
                              <h4 className="text-sm font-bold text-amber-800 dark:text-amber-400 mb-2 uppercase tracking-wide">Key Pointers</h4>
                              <p className="text-base text-justify text-indigo-900 dark:text-indigo-300 whitespace-pre-line leading-relaxed font-medium">
                                {t(topic.ugcNotes[0], topic.ugcNotes[1])}
                              </p>
                            </div>
                            
                            <div className="bg-white/60 dark:bg-gray-900/50 rounded-xl p-4">
                              <h4 className="text-sm font-bold text-amber-800 dark:text-amber-400 mb-2 uppercase tracking-wide">Previous/Expected Questions</h4>
                              <ul className="space-y-2">
                                {topic.ugcQ.map((q, idx) => (
                                  <li key={idx} className="flex gap-2 text-base text-justify text-gray-800 dark:text-gray-200">
                                    <span className="text-amber-500 font-bold">•</span>
                                    {t(q[0], q[1])}
                                  </li>
                                ))}
                              </ul>
                            </div>
                          </div>
                        </section>

                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </div>

      </div>
    </div>
  );
}
